USE DB_SHOPPING_COMPANY
-----------CREATE CUSTOMER TABLE----------------
CREATE TABLE CUSTOMER_DETAIL(CUSTOMER_ID INT PRIMARY KEY IDENTITY,CUST_NAME VARCHAR(20),EMAIL VARCHAR(30),
GENDER VARCHAR(10),MOBILE_NO INT,ADDRESS VARCHAR(100),CITY VARCHAR(20),PINCODE INT)

-----------CREATE CATEGORY TABLE---------------------
CREATE TABLE CATEGORY(CATEGORY_ID INT PRIMARY KEY IDENTITY,CATEGORY_NAME VARCHAR(50),
CATEGORY_IMAGE NVARCHAR(50),CATEGORY_DESC VARCHAR(50))

------------CREATE PRODUCT TABLE--------------
CREATE TABLE PRODUCT(PRODUCT_ID INT PRIMARY KEY IDENTITY,PRODUCT_NAME VARCHAR(50),PRODUCT_DESC VARCHAR(100),
IMAGE1 NVARCHAR(50),IMAGE2 NVARCHAR(50),PRICE INT,STOCK INT,CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID))
-----------CREATE ORDER TABLE--------------

CREATE TABLE ORDER_TAB(ORDER_ID INT PRIMARY KEY,ORDER_NO INT IDENTITY,ORDER_DATE DATETIME,ORDER_TOTAL INT,
CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER_DETAIL(CUSTOMER_ID),SHIPPING_DATE DATETIME,IS_DELIVERED VARCHAR(50))

-----------CREATE TABLE ORDER_DETAIL-----------
CREATE TABLE ORDER_DETAIL(ORDER_DETAIL_ID INT PRIMARY KEY IDENTITY,PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCT(PRODUCT_ID),
PRODUCT_QTY INT,PRODUCT_PRICE INT,ORDER_ID INT FOREIGN KEY REFERENCES ORDER_TAB(ORDER_ID))
DROP PROC ADD_CUSTOMER_ADDRESS
--------SHOW ALL TABLE-------
SELECT * FROM CUSTOMER_DETAIL
SELECT * FROM CATEGORY
SELECT * FROM PRODUCT
SELECT * FROM ORDER_TAB
SELECT * FROM ORDER_DETAIL
SELECT * FROM DB_ERRORS
----------------------------
EXECUTE SP_CUSTOMER_DTLS 'AJAY SHARMA','AJAYG@GMAIL.COM','MALE','7536992471','11,GARSAN SAIYAN',
'AGRA',283124,'ELECTRONICS','NOT AVAILABLE','AUDIO PLAYER','2022-10-15',10,
--------------------CREATE PROCEDURE--------------------
ALTER PROC SP_CUSTOMER_DTLS @CUST_NAME VARCHAR(20),@EMAIL VARCHAR(30),
@GENDER VARCHAR(10),@MOBILE_NO VARCHAR(20),@ADDRESS VARCHAR(100),@CITY VARCHAR(20),@PINCODE INT,@CATEGORY_NAME VARCHAR(50),
@CATEGORY_IMAGE NVARCHAR(50),@CATEGORY_DESC VARCHAR(50),@ORDER_DATE DATETIME,@ORDER_TOTAL INT,
@CUSTOMER_ID INT,@SHIPPING_DATE DATETIME,@IS_DELIVERED VARCHAR(50)
AS
BEGIN
BEGIN TRY
BEGIN TRANSACTION TRAN_CUST_CATEG
INSERT INTO CUSTOMER_DETAIL (CUST_NAME,EMAIL,GENDER,MOBILE_NO,ADDRESS,CITY,PINCODE)
VALUES(@CUST_NAME,@EMAIL,@GENDER,@MOBILE_NO,@ADDRESS,@CITY,@PINCODE)

INSERT INTO CATEGORY(CATEGORY_NAME,CATEGORY_IMAGE,CATEGORY_DESC) 
VALUES(@CATEGORY_NAME,@CATEGORY_IMAGE,@CATEGORY_DESC)

INSERT INTO ORDER_TAB(ORDER_DATE,ORDER_TOTAL,CUSTOMER_ID,SHIPPING_DATE,IS_DELIVERED)
VALUES(@ORDER_DATE,@ORDER_TOTAL,@CUSTOMER_ID,@SHIPPING_DATE,@IS_DELIVERED)
COMMIT TRANSACTION TRAN_CUST_CATEG
END TRY

BEGIN CATCH
ROLLBACK TRANSACTION TRAN_CUST_CATEG
INSERT INTO DB_ERRORS(USER_NAME,ERROR_NUMBER,ERROR_STATE,ERROR_SEVERITY,ERROR_LINE,ERROR_PROCEDURE,ERROR_MESSAGE)
VALUES(SUSER_NAME(),ERROR_NUMBER(),ERROR_STATE(),ERROR_SEVERITY(),ERROR_LINE(),ERROR_PROCEDURE(),ERROR_MESSAGE())
END CATCH
END
